name: Docker自动构建

on:
  push:
    tags:
      - 'v*'
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: abczhou/nas-music

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # 手动触发时使用时间戳
            VERSION="manual-$(date +%Y%m%d%H%M%S)"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Tag 触发时使用 tag 名称
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION=${VERSION#v}
          else
            # 分支推送时使用分支名和 commit SHA
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g')
            SHORT_SHA=$(git rev-parse --short HEAD)
            VERSION="${BRANCH_NAME}-${SHORT_SHA}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64

      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} \
            -t ${{ env.IMAGE_NAME }}:latest \
            --push \
            -f ./Dockerfile .
